#!/bin/bash

set -e

all_args="$*"
host=$(uname -m)
CRIU_BIN=criu-org

target_arch=""
outdir="."
_options=()
_help=0
DUMP=false
while [ "$#" -gt 0 ]
do
        case "$1" in
        --arch)
		target_arch=$2
                shift
                ;;
	dump)
		DUMP=true
	        _options+=("$1")
                ;;
	-D|--image-dir)
		outdir=$2
	        _options+=("$1")
	        _options+=("$2")
                shift
                ;;
        -h|--help)
		_help=1
                ;;
        # an option argument, continue
        *)      
	      _options+=("$1")
              ;;
        esac
        shift
done

if [ "$_help" = "1" ]
then
	echo "[criu-het has the same usage as $CRIU_BIN except for the add option --arch (see below)]"
	$CRIU_BIN -h
	echo -e "  --arch architecture\tthis option create an additional folder containing \n  \t\t\tthe target architecture dump (x86_64 or aarch64)"
	exit
fi

options="${_options[@]}"
#echo "All options:" $options

export CRIU_TARGET_ARCH=$target_arch
function local_checkpoint()
{
	options=$1
	#echo "executing $CRIU_BIN with params: $options"
	$CRIU_BIN $options
}

function het_checkpoint()
{
	options=$1
	target_arch=$2
	outdir=$3

	export CRIU_TARGET_ARCH=$target_arch
	#echo "executing $CRIU_BIN with params: $options"

	$CRIU_BIN $options
	if [ -z $outdir ]; then
		target_outdir=$target_arch
	else
		target_outdir=$outdir/$target_arch
	fi
	crit recode -t $target_arch -d $outdir -o $target_outdir 
}

if [ -z $target_arch ] || [ "$target_arch" = "$host" ] || [ "$DUMP" == false ]
then
	local_checkpoint "$options"
else
	het_checkpoint "$options" $target_arch "$outdir"
fi
